name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 10.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^6.0.3
  google_fonts: ^5.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12

  # FIREBASE
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  firebase_remote_config: ^4.2.5
  cloud_firestore: ^4.8.5

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.1

  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.7

  # IMAGE
  image_picker: ^1.0.2
  photo_view: ^0.14.0
  lottie: ^2.6.0

  # OTHER
  country_picker: ^2.0.20
  flutter_custom_tabs: ^1.0.4
  permission_handler: ^10.3.0
  flutter_html: ^3.0.0-alpha.5
  firebase_pagination: ^3.0.0
  webview_flutter: ^4.2.2

  # SOCIAL LOGIN
  google_sign_in: ^6.1.4
  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.8
  flutter_stripe: ^9.3.0
  cinetpay: ^1.0.7

  #  flutter_braintree: ^3.0.0 Remove due to play store does not approving the app

  # MAP
  google_maps_flutter: ^2.4.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/ic_launcher.png"
  adaptive_icon_foreground: "assets/ic_launcher.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/services/

